export { default as Tema1 } from '../pages/Tema1';
export { default as Tema2 } from '../pages/Tema2';
export { default as Tema3 } from '../pages/Tema3';
export { default as Tema4 } from '../pages/Tema4';
export { default as Tema5 } from '../pages/Tema5';
export { default as Tema6 } from '../pages/Tema6';
export { default as Tema7 } from '../pages/Tema7';
export { default as Tema8 } from '../pages/Tema8';
export { default as Tema9 } from '../pages/Tema9';
